p1805_hw2_lmp2234
================
Lisa Pardee
2024-10-02

\##Question 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)
```

\##Reading in the NYC Transit Subway File

``` r
subway_df = read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
subway_df = janitor::clean_names(subway_df)
```

\##Keeping Certain Variables and Changing Entry to a Logical Variable

``` r
subway_df <-subway_df %>%
select(line:vending,ada)

subway_df = subway_df %>%
  mutate(entry_logical = case_match(entry,
                                    "YES" ~ TRUE,
                                    "NO" ~ FALSE))

subway_df
```

    ## # A tibble: 1,868 × 21
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 14 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <chr>, exit_only <chr>, vending <chr>,
    ## #   ada <lgl>, entry_logical <lgl>

``` r
skimr::skim(subway_df)
```

|                                                  |           |
|:-------------------------------------------------|:----------|
| Name                                             | subway_df |
| Number of rows                                   | 1868      |
| Number of columns                                | 21        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |           |
| Column type frequency:                           |           |
| character                                        | 13        |
| logical                                          | 2         |
| numeric                                          | 6         |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |           |
| Group variables                                  | None      |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| line          |         0 |          1.00 |   5 |  17 |     0 |       36 |          0 |
| station_name  |         0 |          1.00 |   4 |  39 |     0 |      356 |          0 |
| route1        |         0 |          1.00 |   1 |   2 |     0 |       24 |          0 |
| route2        |       848 |          0.55 |   1 |   2 |     0 |       20 |          0 |
| route3        |      1374 |          0.26 |   1 |   2 |     0 |       18 |          0 |
| route4        |      1547 |          0.17 |   1 |   1 |     0 |       13 |          0 |
| route5        |      1630 |          0.13 |   1 |   1 |     0 |       12 |          0 |
| route6        |      1741 |          0.07 |   1 |   1 |     0 |        7 |          0 |
| route7        |      1788 |          0.04 |   1 |   2 |     0 |        7 |          0 |
| entrance_type |         0 |          1.00 |   4 |   9 |     0 |        7 |          0 |
| entry         |         0 |          1.00 |   2 |   3 |     0 |        2 |          0 |
| exit_only     |      1812 |          0.03 |   3 |   3 |     0 |        1 |          0 |
| vending       |         0 |          1.00 |   2 |   3 |     0 |        2 |          0 |

**Variable type: logical**

| skim_variable | n_missing | complete_rate | mean | count               |
|:--------------|----------:|--------------:|-----:|:--------------------|
| ada           |         0 |             1 | 0.25 | FAL: 1400, TRU: 468 |
| entry_logical |         0 |             1 | 0.94 | TRU: 1753, FAL: 115 |

**Variable type: numeric**

| skim_variable     | n_missing | complete_rate |   mean |   sd |     p0 |    p25 |    p50 |    p75 |   p100 | hist  |
|:------------------|----------:|--------------:|-------:|-----:|-------:|-------:|-------:|-------:|-------:|:------|
| station_latitude  |         0 |          1.00 |  40.73 | 0.07 |  40.58 |  40.69 |  40.73 |  40.77 |  40.90 | ▂▅▇▃▂ |
| station_longitude |         0 |          1.00 | -73.94 | 0.06 | -74.03 | -73.99 | -73.96 | -73.91 | -73.76 | ▇▆▃▂▁ |
| route8            |      1820 |          0.03 |   2.98 | 1.94 |   1.00 |   1.00 |   4.00 |   5.00 |   5.00 | ▇▁▁▂▇ |
| route9            |      1840 |          0.01 |   2.54 | 1.17 |   2.00 |   2.00 |   2.00 |   2.00 |   5.00 | ▇▁▁▁▂ |
| route10           |      1845 |          0.01 |   3.00 | 0.00 |   3.00 |   3.00 |   3.00 |   3.00 |   3.00 | ▁▁▇▁▁ |
| route11           |      1845 |          0.01 |   7.00 | 0.00 |   7.00 |   7.00 |   7.00 |   7.00 |   7.00 | ▁▁▇▁▁ |

\#The NYC Subway dataset contains 1868 rows and 21 columns after
retaining specific variable names and adding an additional variable
“entry_logical” that converted the entry variable from character to
logical. The dataset contains information about subway lines, station
names, latitude/longitude, the routes the subways take, entrance type,
whether the station allows entry or is exit only, whether the station
has vending, and whether it is ADA compliant. The variable names were
cleaned using clean_names from the janitor function, only columns “line”
through “vending” and “ada” were retained, and case_match was used to
convert entry to a logical variable. This data is tidy since each
variable has a column name and the observations are organized by rows.
Only relevant information about subway lines, routes, and station
features are retained.

\##How Many Distinct Stations Are There

``` r
distinct_stations <- subway_df %>%
  distinct(station_name, line) %>%
  nrow()

distinct_stations
```

    ## [1] 465

\##How Many Stations are ADA Compliant

``` r
ada_compliant_stations <- subway_df %>%
  filter(ada == TRUE) %>%
  distinct (station_name) %>%
   nrow()

ada_compliant_stations
```

    ## [1] 73

\##What proportion of station entrances/exits without vending allow
entrance

``` r
proportion_entry <- subway_df %>%
  filter (vending == "No")  %>%
   summarise(proportion = mean(entry_logical, na.rm = TRUE)) 

proportion_entry
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1        NaN

``` r
subway_df <- subway_df %>%
  mutate(across(starts_with("route"), as.character))

subway_long <- subway_df %>%
  pivot_longer(
    route1:route11, 
    names_to = "route_name", 
    values_to = "route_number")

subway_long
```

    ## # A tibble: 20,548 × 12
    ##    line     station_name station_latitude station_longitude entrance_type entry
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>         <chr>
    ##  1 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ##  2 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ##  3 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ##  4 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ##  5 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ##  6 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ##  7 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ##  8 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ##  9 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ## 10 4 Avenue 25th St                  40.7             -74.0 Stair         YES  
    ## # ℹ 20,538 more rows
    ## # ℹ 6 more variables: exit_only <chr>, vending <chr>, ada <lgl>,
    ## #   entry_logical <lgl>, route_name <chr>, route_number <chr>

``` r
a_stations <- subway_long %>%
  filter(route_number=="A") %>%  
  distinct(station_name, line) %>%
  nrow()

a_stations
```

    ## [1] 60

``` r
ada_compliant <-subway_long  %>%
  filter (route_number=="A", ada == TRUE) %>%
  distinct(station_name, line) %>%
  nrow()

ada_compliant
```

    ## [1] 17

\##Question 2

``` r
library(readxl)


mrtrashwheel_df <- read_excel("./data/202409 Trash Wheel Collection Data.xlsx", 
                               sheet = "Mr. Trash Wheel", 
                               skip = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(sports_balls = as.integer(round(sports_balls))) |> 
  select(-x15, -x16)  
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
head(mrtrashwheel_df, 5)
```

    ## # A tibble: 5 × 14
    ##   dumpster month year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ## 2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ## 3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ## 4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ## 5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

``` r
professortrashwheel_df <- read_excel("./data/202409 Trash Wheel Collection Data.xlsx", 
                               sheet = "Professor Trash Wheel", 
                               skip = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster)|>  
  mutate(year = as.character(year))

head(professortrashwheel_df, 5)
```

    ## # A tibble: 5 × 13
    ##   dumpster month    year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr>    <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 January  2017  2017-01-02 00:00:00        1.79                 15
    ## 2        2 January  2017  2017-01-30 00:00:00        1.58                 15
    ## 3        3 February 2017  2017-02-26 00:00:00        2.32                 18
    ## 4        4 February 2017  2017-02-26 00:00:00        3.72                 15
    ## 5        5 February 2017  2017-02-28 00:00:00        1.45                 15
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

``` r
gwynndatrashwheel_df <- read_excel("./data/202409 Trash Wheel Collection Data.xlsx", 
                               sheet = "Gwynnda Trash Wheel", 
                               skip = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
mutate(year = as.character(year))

head(gwynndatrashwheel_df, 5)
```

    ## # A tibble: 5 × 12
    ##   dumpster month year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 July  2021  2021-07-03 00:00:00        0.93                 15
    ## 2        2 July  2021  2021-07-07 00:00:00        2.26                 15
    ## 3        3 July  2021  2021-07-07 00:00:00        1.62                 15
    ## 4        4 July  2021  2021-07-16 00:00:00        1.76                 15
    ## 5        5 July  2021  2021-07-30 00:00:00        1.53                 15
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

\##Combining the datasets

``` r
mrtrashwheel_df <- mrtrashwheel_df |> 
  mutate(source = "Mr. Trash Wheel") 

professortrashwheel_df <- professortrashwheel_df |> 
  mutate(source = "Professor Trash Wheel") 

gwynndatrashwheel_df <- gwynndatrashwheel_df |> 
  mutate(source = "Gwynndat Trash Wheel")

combined_df = bind_rows(mrtrashwheel_df, professortrashwheel_df, gwynndatrashwheel_df)

combined_df
```

    ## # A tibble: 1,033 × 15
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,023 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, source <chr>

The `combined_df` dataset consists of 1033 observations and 15 variables
from three datasheets: Mr. Trash Wheel, Gwynnda Trash Wheel, and
Professor Trash Wheel. The `Mr. Trash Wheel` dataset has 651
observations. The `Professor Trash Wheel` dataset has 119 observations.
The `Gwynnda Trash Wheel` dataset has 263 observations. Key variables in
this set include the `date` of trash collection, the `weight_tons` which
notes the weight of the trash collected, and the contents of what was
collected in the trash such as number of `cigarette_butts`. The total
weight of trash collected by `Professor Trash Wheel` is 246.74 pounds.
In June 2022, `Gwynnda Trash Wheel` collected 18,120 cigarette butts.

\##Question 3

``` r
bakers_df <- read_csv("./data/bakers.csv") %>%
  janitor::clean_names() %>%
  rename(baker = baker_name)
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bakes_df <- read_csv("./data/bakes.csv") %>%
  janitor::clean_names()
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
results_df <- read_csv("./data/results.csv", skip = 2) %>%
  janitor::clean_names()
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(bakers_df, 5)
```

    ## # A tibble: 5 × 5
    ##   baker            series baker_age baker_occupation   hometown                 
    ##   <chr>             <dbl>     <dbl> <chr>              <chr>                    
    ## 1 Ali Imdad             4        25 Charity worker     Saltley, Birmingham      
    ## 2 Alice Fevronia       10        28 Geography teacher  Essex                    
    ## 3 Alvin Magallanes      6        37 Nurse              Bracknell, Berkshire     
    ## 4 Amelia LeBruin       10        24 Fashion designer   Halifax                  
    ## 5 Andrew Smyth          7        25 Aerospace engineer Derby / Holywood, County…

``` r
head(bakes_df, 5)
```

    ## # A tibble: 5 × 5
    ##   series episode baker     signature_bake                           show_stopper
    ##    <dbl>   <dbl> <chr>     <chr>                                    <chr>       
    ## 1      1       1 Annetha   Light Jamaican Black Cakewith Strawberr… Red, White …
    ## 2      1       1 David     Chocolate Orange Cake                    Black Fores…
    ## 3      1       1 Edd       Caramel Cinnamon and Banana Cake         N/A         
    ## 4      1       1 Jasminder Fresh Mango and Passion Fruit Hummingbi… N/A         
    ## 5      1       1 Jonathan  Carrot Cake with Lime and Cream Cheese … Three Tiere…

``` r
head(results_df, 5)
```

    ## # A tibble: 5 × 5
    ##   series episode baker     technical result
    ##    <dbl>   <dbl> <chr>         <dbl> <chr> 
    ## 1      1       1 Annetha           2 IN    
    ## 2      1       1 David             3 IN    
    ## 3      1       1 Edd               1 IN    
    ## 4      1       1 Jasminder        NA IN    
    ## 5      1       1 Jonathan          9 IN
